#! /bin/sh

claude --model fable -p "Search for bugs and performance issues in this repository.  For each problem identified raise a github issue immediately; tag it AI-Work and assign it a prioriy based on its severity."
