#! /bin/bash

die() {
    if [ -t 2 ]; then
        printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    else
        printf '\n✗ %s\n' "$*" >&2
    fi
    exit 1
}

success() {
    if [ -t 1 ]; then
        printf '\n\033[32m✓\033[0m %s\n' "$*"
    else
        printf '\n✓ %s\n' "$*"
    fi
}

info() {
    if [ -t 1 ]; then
        printf '\n\033[32m→\033[0m %s\n' "$*"
    else
        printf '\n→ %s\n' "$*"
    fi
}

NAMES=()
URLS=()

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -S|--source)
      NAME="$2"
      URL="$3"

      NAMES+=("$NAME")
      URLS+=("$URL")

      shift # past argument
      shift # past value 1 (Name)
      shift # past value 2 (Url)
      ;;

    *)    # unknown option - skip here
      shift # past argument
      ;;
  esac
done

NUGET_CONF_DIR=$HOME/.nuget/NuGet
NUGET_CONF_FILE="$NUGET_CONF_DIR/NuGet.Config"

[ -d "$NUGET_CONF_DIR" ] && mkdir -p "$NUGET_CONF_DIR"

info "NuGet.Config: $NUGET_CONF_FILE"

{
  echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
  echo "<configuration>"
  echo "  <packageSources>"
  for index in "${!NAMES[@]}"; do
    NAME="${NAMES[$index]}"
    URL="${URLS[$index]}"
    echo "    <add key=\"$NAME\" value=\"$URL\" protocolVersion=\"3\" />"
  done
  echo "  </packageSources>"
  echo "</configuration>"
}

success "Completed"
