#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR=$(dirname "$(readlink -f "$0")")

PRERELEASE=0
RELEASE=0
CLEAR="http-cache"
while [ $# -gt 0 ]; do
    key="$1"

  case $key in
    -a|--all)
      CLEAR="all"
      shift # past argument
      ;;
    -p|--pre-release)
      PRERELEASE=1
      shift # past argument
      ;;
    -r|--release)
      RELEASE=1
      shift # past argument
      ;;      
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

PACK=0  
HAS_PACKED=$(grep -R "<IsPackable>true</IsPackable>" . --include *.csproj | head -1)
if [ -n "$HAS_PACKED" ]; then
  PACK=1
fi

BASEDIR=$(dirname "$(readlink -f "$0")")
SOLUTION=$(find "$PWD" -type f -iname "*.sln" | head -1)
[ -z "$SOLUTION" ] && SOLUTION=$(find "$PWD" -type f -iname "*.slnx" | head -1)
[ -z "$SOLUTION" ] && die "No Solution found in $(pwd)"

SOURCE_DIR=$(dirname "$SOLUTION");
[ -z "$SOURCE_DIR" ] && die "No Solution dir found in $SOURCE_DIR"


echo "***** Clearing NuGet cache ($CLEAR)... *****" 
dotnet nuget locals "$CLEAR" --clear  || die "######## Nuget Clear $CLEAR Failed ########"

echo "***** Restoring... *****" 
dotnet tool restore  || die "######## Tool Restore Failed ########"

echo "***** Checking... *****" 
$BASEDIR/buildcheck  || die "######## Build Check Failed ########"

cd "$SOURCE_DIR" || die "Could not change to $SOURCE_DIR"

RULESET_TYPE=NONE
RULESET_FILE=
RULESET_ADJUSTMENT_FILE=
if [ -f "$SOURCE_DIR/CodeAnalysis.ruleset" ]; then
  RULESET_TYPE=ruleset
  RULESET_FILE="$SOURCE_DIR/CodeAnalysis.ruleset"

fi

if [ -f "$SOURCE_DIR/../.globalconfig" ]; then
  RULESET_TYPE=ruleset
  RULESET_FILE="$SOURCE_DIR/../.globalconfig"

fi



RESTORE=0
if [ "$RULESET_TYPE" != "NONE" ]; then

    if [ "$PRERELEASE" = "1" ] && 
          [ -f "$SOURCE_DIR/pre-release.rule-settings.json" ]; then
        RULESET_ADJUSTMENT_FILE="$SOURCE_DIR/pre-release.rule-settings.json"
    elif [ "$RELEASE" = "1" ] && 
       [ -f "$SOURCE_DIR/release.rule-settings.json" ]; then
    
        RULESET_ADJUSTMENT_FILE="$SOURCE_DIR/pre-release.rule-settings.json"      
        RESTORE=1
    fi

    [ -n "$RULESET_ADJUSTMENT_FILE" ] && \
        dotnet code-analysis "$RULESET_TYPE" \
                    --ruleset "$RULESET_FILE" \
                    --changes "$RULESET_ADJUSTMENT_FILE" || die "Failed to update $RULESET_FILE"

    RESTORE=1
fi

echo "***** Restoring... *****" 
dotnet restore  || die "######## Restore Failed ########"

echo "***** Checking for package vulnerabilities... *****" 
SOURCES="--source https://api.nuget.org/v3/index.json"
for SOURCE in $(dotnet nuget list source | grep https:// | awk '{$1=$1;print}');
do
  SOURCES="$SOURCES --source $SOURCE"
done
echo "Sources: $SOURCES"
SolutionDir="$SOURCE_DIR/" dotnet list "$SOLUTION" package --vulnerable --include-transitive $SOURCES || die "Vulnerabilities found"

echo "***** Cleaning... *****" 
dotnet clean  \
          "--nowarn:MSB4241" || die "######## Clean Failed ########"

echo "***** Building... *****" 
dotnet build \
          --warnaserror \
          --configuration Release \
           --no-restore \
          "-p:ApiCompatGenerateSuppressionFile=true" \
          "-p:ContinuousIntegrationBuild=true" \
          "-p:IsProduction=false" \
          "--nowarn:MSB4241" \
          "-p:Optimize=true" \
          "-p:SuppressNETCoreSdkPreviewMessage=true" \
          "-p:Version=0.0.0.1-test" \
           -nodeReuse:False || die "######## Build Failed ########"

echo "***** Testing... *****" 
dotnet test \
          --configuration Release \
           --no-restore \
           --no-build \
           --long-running 10 \
          "-p:ApiCompatGenerateSuppressionFile=true" \
          "-p:ContinuousIntegrationBuild=true" \
          "-p:IsProduction=false" \
          "-p:Optimize=true" \
          "-p:SuppressNETCoreSdkPreviewMessage=true" \
          "-p:Version=0.0.0.1-test" \
          || die "######## Tests Failed ########"

if [ "$PACK" = "1" ]; then          
  echo "***** Packing... *****" 
  dotnet pack \
            --warnaserror \
            --configuration Release \
           --no-restore \
            "-p:ApiCompatGenerateSuppressionFile=true" \
            "-p:ContinuousIntegrationBuild=true" \
            "-p:IncludeSymbols=False" \
            "-p:IsProduction=false" \
            "--nowarn:MSB4241" \
            "-p:Optimize=true" \
            "-p:SuppressNETCoreSdkPreviewMessage=true" \
            "-p:Version=0.0.0.1-test" \
            -nodeReuse:False || die "######## Packing Failed ########"
fi

[ "$RESTORE" = "1" ] && git checkout "$RULESET_ADJUSTMENT_FILE"

echo "***** Completed *****" 


 
