#! /bin/sh

die() {
    if [ -t 2 ]; then
        printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    else
        printf '\n✗ %s\n' "$*" >&2
    fi
    exit 1
}

success() {
    if [ -t 1 ]; then
        printf '\n\033[32m✓\033[0m %s\n' "$*"
    else
        printf '\n✓ %s\n' "$*"
    fi
}

info() {
    if [ -t 1 ]; then
        printf '\n\033[32m→\033[0m %s\n' "$*"
    else
        printf '\n→ %s\n' "$*"
    fi
}

SCRIPT_NAME=$(basename "$0")
GLOBAL_HOOKS=$(git config --global core.hooksPath 2>/dev/null)
if [ -n "$GLOBAL_HOOKS" ]; then
    GLOBAL_SCRIPTS=$(dirname "$GLOBAL_HOOKS")/scripts
    if [ -x "$GLOBAL_SCRIPTS/$SCRIPT_NAME" ]; then
        info "Using global pre-commit script: $GLOBAL_SCRIPTS/$SCRIPT_NAME"
        exec "$GLOBAL_SCRIPTS/$SCRIPT_NAME" "$@"
    fi
fi
SYSTEM_HOOKS=$(git config --system core.hooksPath 2>/dev/null)
if [ -n "$SYSTEM_HOOKS" ]; then
    SYSTEM_SCRIPTS=$(dirname "$SYSTEM_HOOKS")/scripts
    if [ -x "$SYSTEM_SCRIPTS/$SCRIPT_NAME" ]; then
        info "Using system pre-commit script: $SYSTEM_SCRIPTS/$SCRIPT_NAME"
        exec "$SYSTEM_SCRIPTS/$SCRIPT_NAME" "$@"
    fi
fi
info "Using local $SCRIPT_NAME"

SOLUTION=$(find "$PWD" -type f -iname "*.sln" | head -1)
[ -z "$SOLUTION" ] && SOLUTION=$(find "$PWD" -type f -iname "*.slnx" | head -1)
[ -z "$SOLUTION" ] && die "No Solution found in $(pwd)"

info "Running build check on ${SOLUTION}"
dotnet buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild true || die "Check failed"
success "Build check passed"
