#! /bin/bash

die() {
    echo
    echo "$@"
    exit 1
}



NAMES=()
URLS=()

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -S|--source)
      NAME="$2"
      URL="$3"
      
      NAMES+=("$NAME")
      URLS+=("$URL")
      
      shift # past argument
      shift # past value 1 (Name)
      shift # past value 2 (Url)      
      ;;
    
    *)    # unknown option - skip here      
      shift # past argument
      ;;
  esac
done

  
NUGET_CONF_DIR=$HOME/.nuget/NuGet
NUGET_CONF_FILE="$NUGET_CONF_DIR/NuGet.Config"

[ -d "$NUGET_CONF_DIR" ] && mkdir -p "$NUGET_CONF_DIR"

echo "NuGet.Config: $NUGET_CONF_FILE"

{
  echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
  echo "<configuration>"
  echo "  <packageSources>"
  for index in ${!NAMES[@]}; do
    NAME="${NAMES[$index]}"
    URL="${URLS[$index]}"
    echo "    <add key=\"$NAME\" value=\"$URL\" protocolVersion=\"3\" />"
  done
  echo "  </packageSources>"
  echo "</configuration>"
 
}
