#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}


LEGACY_SOLUTION=$(find "$PWD" -type f -iname "*.sln" | head -1)
[ -z "$LEGACY_SOLUTION" ] && die "No Solution found in $(pwd)"

NEW_SOLUTION=$(find "$PWD" -type f -iname "*.slnx" | head -1)
[ -z "$NEW_SOLUTION" ] || die "SolutionX found in $(pwd)"

dotnet sln migrate || die "Migration failed"

NEW_SOLUTION=$(find "$PWD" -type f -iname "*.slnx" | head -1)
[ -z "$NEW_SOLUTION" ] && die "No SolutionX found in $(pwd) after migration"

echo ""

if [ -f "$NEW_SOLUTION" ]; then
  [ -f "$LEGACY_SOLUTION" ] && rm -f "$LEGACY_SOLUTION"
  [ -f "$LEGACY_SOLUTION.DotSettings" ] && mv "$LEGACY_SOLUTION.DotSettings" "$NEW_SOLUTION.DotSettings"
  [ -f "$LEGACY_SOLUTION.DotSettings.user" ] && mv "$LEGACY_SOLUTION.DotSettings.user" "$NEW_SOLUTION.DotSettings.user"
fi
 