version: '3.9'
services:
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 16000:16000
      - 26000:26000
    volumes:
      - isos:/app/iso
      - config:/app/data
    environment:
      - AUTO_START_PXE=true
    

  build:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        IVENTOY: 1.0.19
      args:
        IVENTOY: 1.0.19

volumes:
  isos:
    external: true
  config:
    external: true
