".NET update":
 - any: [ 'src/global.json' ]
"C#":
 - any: [ './**/*.cs', './**/*.csproj' ]
"C# Project":
 - any: [ './**/*.csproj' ]
"C# Solution":
 - any: [ './**/*.sln', './**/*.slnx' ]
"Change Log":
 - any: [ 'CHANGELOG.md' ]
"Config Change":
 - any: [ 'src/**/*.json', '!src/global.json' ]
"dotnet":
 - any: [ 'src/**/*.csproj' ]
"Editorconfig":
 - any: [ '.editorconfig' ]
"github-actions":
 - any: [ '.github/actions/*.yml', '.github/workflows/*.yml' ]
"Markdown":
 - any: [ './**/*.md' ]
"Migration Script":
 - any: [ 'tools/MigrationScripts/**/*' ]
"npm":
 - any: [ './**/package-lock.json', './**/package.json' ]
"Powershell":
 - any: [ './**/*.ps1', './**/*.psm1' ]
"Read Me":
 - any: [ 'README.md' ]
"Setup":
 - any: [ 'SETUP.md' ]
"Solidity":
 - any: [ './**/*.sol' ]
"SQL":
 - any: [ './**/*.sql', 'db/**/*' ]
"Static Code Analysis Rules":
 - any: [ '.globalconfig', 'src/CodeAnalysis.ruleset' ]
"Unit Tests":
 - any: [ 'src/*.Tests.*/**/*', 'src/*.Tests.Integration.*/**/*', 'src/*.Tests.Integration/**/*', 'src/*.Tests/**/*' ]
