#! /bin/bash


for line in $(find  $(pwd)/* -name '*.git' -printf '%h\n' | sort -u | grep -v .cache)
do 
  echo "$line"
  CURRENT_DIR=$line  


  echo ""
  echo "Retrieving $CURRENT_DIR..."
  git -C "$CURRENT_DIR" remote get-url origin
  git -C "$CURRENT_DIR" branch -m master main
  git -C "$CURRENT_DIR" fetch origin
  git -C "$CURRENT_DIR" branch -u origin/main main
  git -C "$CURRENT_DIR" remote set-head origin -a
  
  echo " * done"
done