#! /bin/sh
find "$(pwd)"/* -name '*.git' -print | sed "s|/.git$||" | sort -u | grep -v .cache | while IFS= read -r line
do
  echo "$line"
  CURRENT_DIR=$line

  echo ""
  echo "Retrieving $CURRENT_DIR..."
  git -C "$CURRENT_DIR" remote get-url origin 2>&1
  git -C "$CURRENT_DIR" clean -f -d -x 2>&1
  git -C "$CURRENT_DIR" remote update origin --prune 2>&1

  echo " * done"
done
