#! /bin/sh


for line in $(find ${pwd}/* -name '*.git' -print | sed "s|/.git$||" | sort -u | grep -v .cache)
do 
  echo "$line"
  CURRENT_DIR=$line  

  echo ""
  echo "Retrieving $CURRENT_DIR..."
  git -C "$CURRENT_DIR" remote get-url origin 2>&1
  git -C "$CURRENT_DIR" fetch --prune --prune-tags 2>&1
  git -C "$CURRENT_DIR" remote update origin --prune 2>&1
  
  git -C "$CURRENT_DIR" status 2>&1
  if [ $? -eq 0 ]
  then
    echo " + No pending changes in working folder. Rebasing..."
    git -C "$CURRENT_DIR" rebase 2>&1
    git -C "$CURRENT_DIR" rebase --abort 2>&1 > /dev/null
  fi 

  echo " * done"
done
