#! /bin/bash
REGEX_CHANGELOG="^([0-9a-zA-Z]*)\s.*Changelog\sfor\s([0-9]*\.[0-9]*\.[0-9]*)$"

matchingBranch() {
  CHANGE_RELEASE=$1
  SEARCH_BRANCH="origin/release/$CHANGE_RELEASE"
  git branch --remote | while read -r BRANCH; do
    #echo "SRC: $BRANCH"
    if [[ "$BRANCH" = "$SEARCH_BRANCH" ]]; then
      echo "Y"
      break
    fi
  done
 }
 
git log --oneline | while read -r CHANGE; do 
  if [[ $CHANGE =~ $REGEX_CHANGELOG ]]; then
    CHANGE_HASH="${BASH_REMATCH[1]}"
    CHANGE_RELEASE="${BASH_REMATCH[2]}"

    FOUND=$(matchingBranch "$CHANGE_RELEASE") 
    if [ "$FOUND" = "Y" ]; then
      echo "* Found Release $CHANGE_RELEASE at in release/$CHANGE_RELEASE at $CHANGE_HASH"
    else 
      echo "- Missing Release $CHANGE_RELEASE in $CHANGE_HASH"
      git checkout "$CHANGE_HASH" && git checkout -b "release/$CHANGE_RELEASE" && git push
      git switch main || echo "Switching to Main"
      echo "+++ Created branch release/$CHANGE_RELEASE"
    fi
    
  fi
done && echo "OK" || echo "Failed" 
