#! /bin/bash

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

REGEX_CHANGELOG="^([0-9a-zA-Z]*)\s.*Changelog\sfor\s([0-9]*\.[0-9]*\.[0-9]*)$"

matchingBranch() {
  CHANGE_RELEASE=$1
  SEARCH_BRANCH="origin/release/$CHANGE_RELEASE"
  git branch --remote | while read -r BRANCH; do
    if [[ "$BRANCH" = "$SEARCH_BRANCH" ]]; then
      echo "Y"
      break
    fi
  done
 }

if git log --oneline | while read -r CHANGE; do
  if [[ $CHANGE =~ $REGEX_CHANGELOG ]]; then
    CHANGE_HASH="${BASH_REMATCH[1]}"
    CHANGE_RELEASE="${BASH_REMATCH[2]}"

    FOUND=$(matchingBranch "$CHANGE_RELEASE")
    if [ "$FOUND" = "Y" ]; then
      info "Found Release $CHANGE_RELEASE in release/$CHANGE_RELEASE at $CHANGE_HASH"
    else
      info "Missing Release $CHANGE_RELEASE in $CHANGE_HASH"
      git checkout "$CHANGE_HASH" && git checkout -b "release/$CHANGE_RELEASE" && git push
      git switch main || true
      success "Created branch release/$CHANGE_RELEASE"
    fi

  fi
done; then
  success "OK"
else
  die "Failed"
fi
