#! /bin/sh

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"

find "$(pwd)"/* -name '*.git' -print | sed "s|/.git$||" | sort -u | grep -v .cache | while IFS= read -r line
do
  echo "$line"
  CURRENT_DIR=$line

  echo "==== $CURRENT_DIR ==="
  cd "$CURRENT_DIR" && "$BASEDIR/missing-release-branches"

  echo " * done"
done
