#!/bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
info "Script Dir: $BASEDIR"

REPOS=personal
WORKDIR=$HOME/work/$REPOS

[ ! -d "$WORKDIR" ] && mkdir -p "$WORKDIR"

cd "$WORKDIR" || die "Could not switch to $WORKDIR"

curl "https://updates.markridgwell.com/$REPOS-repos.config" -o "$WORKDIR/repos.lst"

clone-repos "$WORKDIR/repos.lst"

fetch
