#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR="$(dirname "$(readlink -f "$0")")"

# shellcheck source=/dev/null
. "$BASEDIR/preview-config"

[ -z "$DOTNET_PREVIEW_VERSION" ] && die "DOTNET_PREVIEW_VERSION not defined"

BRANCH="depends/sdk/dotnet/$DOTNET_PREVIEW_VERSION/preview"

info "Using Branch: $BRANCH"

git fetch && git checkout main && git pull && git checkout "$BRANCH" && git pull && rebase && update-dotnet-sdk
