version: "3.8"
services:
  postgresql:
    image: postgres:16.0
    container_name: postgresql
    volumes:
      - /var/lib/postgres/data:/var/lib/postgresql/data
      - /var/lib/postgres/postgres_password:/run/secrets/postgres-passwd
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
