version: "3.8"
services:
  postgresql:
    image: postgres:16.0
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /var/lib/postgres/postgres_password:/run/secrets/postgres-passwd
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    ulimits:
      nofile:
        soft: 20000
        hard: 20000

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypgadminpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql

volumes:
  postgres_data:
  pgadmin_data:
