#! /bin/bash

die() {
    if [ -t 2 ]; then
        printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    else
        printf '\n✗ %s\n' "$*" >&2
    fi
    exit 1
}

success() {
    if [ -t 1 ]; then
        printf '\n\033[32m✓\033[0m %s\n' "$*"
    else
        printf '\n✓ %s\n' "$*"
    fi
}

info() {
    if [ -t 1 ]; then
        printf '\n\033[32m→\033[0m %s\n' "$*"
    else
        printf '\n→ %s\n' "$*"
    fi
}




BASEDIR="$(dirname "$(readlink -f "$0")")"

REGEX_SHEBANG="^#!\s*(.*)$"


excluded() {
  FILE=$1


  if [ "$FILE" = "$BASEDIR/db/dbenv" ]; then
    echo "1"
  else
    echo "0"
  fi
}

# Find all the script files both executable and ones with shebang
FILES=$({ \
      find "$BASEDIR" -not -path '*/.*' -type f -executable -print || die "Search: find"
      while IFS= read -r SHEBANG_FILE; do
        IFS= read -r FIRST_LINE < "$SHEBANG_FILE" || continue

        case $FIRST_LINE in
          '#!'*)
            printf '%s\n' "$SHEBANG_FILE"
            ;;
        esac
      done < <(find "$BASEDIR" -not -path '*/.*' -type f -print) || die "Search: Shebang"
      } | sort | uniq)

info "Testing:"
for FILE in $FILES; do
  info "* $FILE"
  info "Executable"
  if [ ! -x "$FILE" ]; then
    die "Not Executable"
  fi

  info "Shebang"
  FIRST_LINE=$(head -1 "$FILE")
  if [[ $FIRST_LINE =~ $REGEX_SHEBANG ]]; then
    SHEBANG_EXEC="${BASH_REMATCH[1]}"
    SHELL=
    if [ "$SHEBANG_EXEC" = "/bin/bash" ]; then
      SHELL="bash"
      bash -n -u "$FILE" || die "$SHELL: Invalid Script"
      sh -n "$FILE" > /dev/null 2>&1 && info "Could be run in sh?"
    elif [ "$SHEBANG_EXEC" = "/usr/bin/env bash" ]; then
      SHELL="bash"
      bash -n -u  "$FILE" || die "$SHELL: Invalid Script"
      sh -n "$FILE" > /dev/null 2>&1 && info "Could be run in sh?"
    elif [ "$SHEBANG_EXEC" = "/bin/sh" ]; then
      SHELL="sh"
      sh -n "$FILE" || die "$SHELL: Invalid Script"
    elif [ "$SHEBANG_EXEC" = "/usr/bin/env sh" ]; then
      SHELL="sh"
      sh -n "$FILE" || die "$SHELL: Invalid Script"
    else
      die "Unknown Shell: $SHEBANG_EXEC"
    fi


  else
    die "No Shebang: $FIRST_LINE"
  fi

  ## Run Shellcheck on the file
  if [ "$(excluded "$FILE")" = "1" ]; then
    info "Excluded from shellcheck"
  else
    shellcheck "$FILE" || die "Shellcheck"
  fi

done
