#! /bin/bash

die() {
    echo "$@"
    exit 1
}

testing() {
  echo " + $*"
}

hint() {
    echo "  ? CHECK: $*"
}

fail() {
    echo "  - ERROR: $*"
    exit 1
  
}



BASEDIR="$(dirname "$(readlink -f "$0")")"

REGEX_SHEBANG="^#!\s*(.*)$"

# Find all the script files both executable and ones with shebang
FILES=$({ \
      find "$BASEDIR" -not -path '*/.*' -type f -executable -print || die "Search: find"
      grep -rIzl --exclude-dir='.*' '^#![[:blank:]]' "$BASEDIR" || die "Search: Grep"
      } | sort | uniq)

echo "Testing:"
for FILE in $FILES; do
  echo "* $FILE"
  testing "Executable"
  if [ ! -x "$FILE" ]; then
    fail "Not Executable"
  fi
  
  testing "Shebang"
  FIRST_LINE=$(head -1 "$FILE")
  if [[ $FIRST_LINE =~ $REGEX_SHEBANG ]]; then
    SHEBANG_EXEC="${BASH_REMATCH[1]}"
    SHELL=
    if [[ "$SHEBANG_EXEC" == "/bin/bash" ]]; then
      SHELL=bash
      bash -n "$FILE" || fail "$SHELL: Invalid Script"
      sh -n "$FILE" > /dev/null 2>&1 && hint "Could be run in bash?"
    elif [[ "$SHEBANG_EXEC" == "/usr/bin/env bash" ]]; then
      SHELL=bash
      bash -n "$FILE" || fail "$SHELL: Invalid Script"
      sh -n "$FILE" > /dev/null 2>&1 && hint "Could be run in bash?"
    elif [[ "$SHEBANG_EXEC" == "/bin/sh" ]]; then
      SHELL=sh
      sh -n "$FILE" || fail "$SHELL: Invalid Script"
    elif [[ "$SHEBANG_EXEC" == "/usr/bin/env sh" ]]; then
      SHELL=sh
      sh -n "$FILE" || fail "$SHELL: Invalid Script"
    else
      fail "Unknown Shell: $SHEBANG_EXEC"
    fi
  else
    fail "No Shebang: $FIRST_LINE"
  fi
  
done


   