#! /bin/sh
BASEDIR=$(dirname "$(readlink -f "$0")")
SOLUTION=$(readlink -f *.sln)

die() {
    echo
    echo "$@"
    exit 1
}

[ -z "$SOLUTION" ] && die "No Solution found in $(pwd)"

dotnet buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild true || die "Check failed"
