#! /bin/sh
BASEDIR=$(dirname "$(readlink -f "$0")")
SOLUTION=$(readlink -f *.sln)

[ -z "$SOLUTION" ] && echo "No Solution found in $(pwd)" && exit 1

dotnet buildcheck -Solution "$SOLUTION" -WarningAsErrors true -PreReleaseBuild true
