#! /bin/sh
BASEDIR=$(dirname "$(readlink -f "$0")")

die() {
    echo
    echo "$@"
    exit 1
}


CLEAR="http-cache"
while [ $# -gt 0 ]; do
    key="$1"

  case $key in
    -a|--all)
      CLEAR="all"
      shift # past argument
      ;;
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

PACK=0  
HAS_PACKED=$(grep -R "<IsPackable>true</IsPackable>" . --include *.csproj | head -1)
if [ -n "$HAS_PACKED" ]; then
  PACK=1
fi

echo "***** Clearing NuGet cache ($CLEAR)... *****" 
dotnet nuget locals "$CLEAR" --clear  || die "######## Nuget Clear $CLEAR Failed ########"

echo "***** Restoring... *****" 
dotnet tool restore  || die "######## Tool Restore Failed ########"

echo "***** Checking... *****" 
$BASEDIR/buildcheck  || die "######## Build Check Failed ########"

echo "***** Restoring... *****" 
dotnet restore  || die "######## Restore Failed ########"

echo "***** Cleaning... *****" 
dotnet clean  || die "######## Clean Failed ########"

echo "***** Building... *****" 
dotnet build \
          --warnaserror \
          --configuration Release \
          "-p:Version=0.0.0.1-test" \
          "-p:IsProduction=false" \
          -p:ApiCompatGenerateSuppressionFile=true \
          -nodeReuse:False \
          -p:NoWarn=MSB4241 \
          -p:SuppressNETCoreSdkPreviewMessage=true \
          -p:Optimize=true || die "######## Build Failed ########"

echo "***** Testing... *****" 
dotnet test \
          --warnaserror \
          --configuration Release \
          "-p:Version=0.0.0.1-test" \
          "-p:IsProduction=false" \
          --filter FullyQualifiedName\!~Integration \
          -p:ApiCompatGenerateSuppressionFile=true \
          -nodeReuse:False \
          -p:NoWarn=MSB4241 \
          -p:SuppressNETCoreSdkPreviewMessage=true \
          -p:Optimize=true || die "######## Tests Failed ########"
          
if [ "$PACK" = "1" ]; then          
  echo "***** Packing... *****" 
  dotnet pack \
            --warnaserror \
            --configuration Release \
            "-p:Version=0.0.0.1-test" \
            "-p:IsProduction=false" \
            -p:ApiCompatGenerateSuppressionFile=true \
            -nodeReuse:False \
            -p:IncludeSymbols=False \
            -p:NoWarn=MSB4241 \
            -p:SuppressNETCoreSdkPreviewMessage=true \
            -p:Optimize=true || die "######## Packing Failed ########"
fi

echo "***** Completed *****" 