#! /bin/sh

error_exit() {
    echo
    echo "$@"
    exit 1
}

while [ $# -gt 0 ]; do
  SOURCE="$1"
  OUTPUT="$SOURCE.mov"

  shift # past argument
  
  # -qscale 1    - is ambiguous
  ffmpeg -i "$SOURCE" -vcodec mjpeg -acodec pcm_s16le -f mov "$OUTPUT"

done


