#! /bin/bash
PROG=$0
CURRENTDIR=$PWD
echo "Current Dir: $CURRENTDIR"

function error_exit {
    echo
    echo "$@"
    exit 1
}

while [[ $# -gt 0 ]]; do
  SOURCE="$1"
  OUTPUT="$SOURCE.avi"

  shift # past argument
  
  # -qscale 1    - is ambiguous
  ffmpeg -i "$SOURCE" -vcodec mjpeg -acodec aac -f avi "$OUTPUT"

done


