#! /bin/sh

die() {
    if [ -t 2 ]; then
        printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    else
        printf '\n✗ %s\n' "$*" >&2
    fi
    exit 1
}

success() {
    if [ -t 1 ]; then
        printf '\n\033[32m✓\033[0m %s\n' "$*"
    else
        printf '\n✓ %s\n' "$*"
    fi
}

info() {
    if [ -t 1 ]; then
        printf '\n\033[32m→\033[0m %s\n' "$*"
    else
        printf '\n→ %s\n' "$*"
    fi
}

while [ $# -gt 0 ]; do
  SOURCE="$1"
  OUTPUT="$SOURCE.mov"

  shift # past argument

  info "Converting $SOURCE to $OUTPUT"

  # -qscale 1    - is ambiguous
  ffmpeg -i "$SOURCE" -vcodec mjpeg -acodec pcm_s16le -f mov "$OUTPUT" || die "Failed to convert $SOURCE"

  success "Converted $SOURCE"

done
