#! /bin/bash

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR=$(dirname "$(readlink -f "$0")")

[ -z "$BASEDIR" ] && die "BASEDIR Not defiled"  

PROXY_HOST=http://builds.dotnet.local:5554/dotnet

# update dotnet install scripts

[ -f "$BASEDIR/dotnet-install.sh" ] && rm -f"$BASEDIR/dotnet-install.sh"
echo "Downloading Latest install script"
curl https://dot.net/v1/dotnet-install.sh -L -f -o "$BASEDIR/dotnet-install.sh" || die "Could not download install script"
[ -f "$BASEDIR/dotnet-install.sh" ] || die "dotnet install script failed"

echo "Changing install script to use local proxy cache.."
sed -i "s|https://builds.dotnet.microsoft.com/dotnet|$PROXY_HOST|g" "$BASEDIR/dotnet-install.sh"
sed -i "s|https://ci.dot.net/public|$PROXY_HOST/dotnet|g" "$BASEDIR/dotnet-install.sh"
#sed -i "s|https://aka.ms/dotnet|https://builds.dotnet.local:5555/dotnet|g" "$BASEDIR/dotnet-install.sh"
echo "Changing install script to use local proxy cache..."

chmod +x "$BASEDIR/dotnet-install.sh"

sudo rm -fr /usr/share/dotnet

# update to latest dotnet core
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 6.0
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 7.0
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 8.0
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 9.0

# Install/update powershell
sudo /usr/share/dotnet/dotnet tool update --local PowerShell

# rm -f "$BASEDIR/dotnet-install.sh"
