#! /bin/bash

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR=$(dirname "$(readlink -f "$0")")

[ -z "BASEDIR" ] && die "BASEDIR Not defiled"  


# update dotnet install scripts
curl https://dot.net/v1/dotnet-install.sh -L -o "$BASEDIR/dotnet-install.sh"
[ ! -f "$BASEDIR/dotnet-install.sh" ] && die "dotnet install script failed"

chmod +x "$BASEDIR/dotnet-install.sh"

sudo rm -fr /usr/share/dotnet

# update to latest dotnet core
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 6.0
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 7.0
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 8.0
sudo "$BASEDIR/dotnet-install.sh" --install-dir /usr/share/dotnet -channel 9.0

# Install/update powershell
sudo /usr/share/dotnet/dotnet tool update --local PowerShell

rm -f "$BASEDIR/dotnet-install.sh"