#! /bin/sh

die() {
    if [ -t 2 ]; then
        printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    else
        printf '\n✗ %s\n' "$*" >&2
    fi
    exit 1
}

success() {
    if [ -t 1 ]; then
        printf '\n\033[32m✓\033[0m %s\n' "$*"
    else
        printf '\n✓ %s\n' "$*"
    fi
}

info() {
    if [ -t 1 ]; then
        printf '\n\033[32m→\033[0m %s\n' "$*"
    else
        printf '\n→ %s\n' "$*"
    fi
}

if [ ! -f "$HOME/dotnet-tools.json" ]; then

  cd "$HOME" && dotnet new tool-manifest

fi

[ -f "$HOME/dotnet-tools.json" ] || die "No tool manifest"


TOOLS="sleet \
       TSQLLint \
       FunFair.BuildCheck \
       FunFair.BuildVersion \
       Credfeto.Changelog.Cmd \
       Credfeto.Package.Push \
       Credfeto.Package.Update \
       Credfeto.DotNet.Code.Analysis.Overrides.Cmd \
       Credfeto.DotNet.Repo.Tools.Cmd \
       Credfeto.DotNet.Repo.Formatter \
       FunFair.Content.Packager.Cmd \
       FunFair.Content.PackageSigner.Cmd \
       JetBrains.ReSharper.GlobalTools \
       powershell \
       dotnet-script \
       dotnet-reportgenerator-globaltool \
       csharpier \
       ilspycmd"

for TOOL in $TOOLS; do
   info "Installing $TOOL"
   dotnet tool install --local "$TOOL"
done

success "Done"
