#! /bin/sh
die() {
    echo
    echo "$@"
    exit 1
}


RELEASE=$1

[ -z "$RELEASE" ] && die "Invalid release"

dotnet changelog -c "$RELEASE" && git add CHANGELOG.md && git commit CHANGELOG.md -m"Changelog for $RELEASE" -n && git push
