#! /bin/sh


SSH_KEY_DIR=$HOME/.ssh
SSH_HOSTS_FILE=$SSH_KEY_DIR/config
SSH_KEY_ALGORITHM=ed25519
# TODO: define a sane number here - don't want to wait for the end of time, but needs to be secure
SSH_KEY_ROUNDS=1000000000

# Ensure SSH key directory exists with sane permissions
[ ! -d "$SSH_KEY_DIR" ] && mkdir -p "$SSH_KEY_DIR"
[ -d "$SSH_KEY_DIR" ] && chmod 700 "$SSH_KEY_DIR"

if [ ! -f "$SSH_HOSTS_FILE" ] ;
then
  {
    echo "Host *"
    echo "  # Always use SSH2."
    echo "  Protocol 2"
    echo ""
    echo "  # Prefer public key auth"
    echo "  PasswordAuthentication no"
    echo "  PubkeyAuthentication yes"
    echo "  PreferredAuthentications=publickey"
    echo ""
    echo "  # Require Identity File"
    echo "  IdentitiesOnly yes"  
  } > "$SSH_HOSTS_FILE"
  chmod 600 "$SSH_HOSTS_FILE"
fi 

PROG=$0
BASEDIR="$(dirname "$(readlink -f "$0")")"

die() {
    echo
    echo "$@"
    exit 1
}

[ -f "/bin/ssh-keygen" ] || die "ssh-keygen not found"
[ -f "/bin/sed" ] || die "sed not found"

create_ssh_key() {
  HOST=
  COMMENT=
  SKIP_PASSWORD=0
  while [ $# -gt 0 ]; do
    key="$1"

    case $key in
      -h|--host)
        HOST="$2"
        shift # past argument
        shift # past value
        ;;
      -c|--comment)
        COMMENT="$2"        
        shift # past argument
        shift # past value
        ;;
      -n|--no-password)
        SKIP_PASSWORD=1        
        shift # past argument
        ;;
      *)    # unknown option
        shift # past argument
        ;;
    esac
  done
  
  [ -z "$HOST" ] && die "--host not specified"
  [ -z "$COMMENT" ] && die "--comment not specified"
  
  KEY_BASE_NAME="id_$HOST"
  PRIVATE_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME"
  PUBLIC_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME.pub"
  [ -f "$PRIVATE_KEY_FILENAME" ] && die "Private key already exists: $PRIVATE_KEY_FILENAME"
  [ -f "$PUBLIC_KEY_FILENAME" ] && die "Public key already exists: $PUBLIC_KEY_FILENAME"
  
  echo "Creating new SSH key for $HOST"
  echo "Comment: $COMMENT"
  echo "Private Key: $PRIVATE_KEY_FILENAME"
  echo "Public Key: $PRIVATE_KEY_FILENAME"
  [ "$SKIP_PASSWORD" -eq "1" ] && ssh-keygen -a "$SSH_KEY_ROUNDS" -t "$SSH_KEY_ALGORITHM" -C "$COMMENT" -P "" -f "$PRIVATE_KEY_FILENAME"
  echo ssh-keygen -a "$SSH_KEY_ROUNDS" -t "$SSH_KEY_ALGORITHM" -C "$COMMENT" -f "$PRIVATE_KEY_FILENAME" 
  [ "$SKIP_PASSWORD" -eq "0" ] && ssh-keygen -a "$SSH_KEY_ROUNDS" -t "$SSH_KEY_ALGORITHM" -C "$COMMENT" -f "$PRIVATE_KEY_FILENAME"
  
  # TODO - Check for existing host entry and add missing config if needed
  # TODO - better host processing code
  {
    echo "Host $HOST"
    echo "  IdentityFile ~/.ssh/$KEY_BASE_NAME"
    echo "  IdentitiesOnly yes"
  } >> "$SSH_HOSTS_FILE"
  
  [ -f "$PUBLIC_KEY_FILENAME" ] && cat "$PUBLIC_KEY_FILENAME"
}

alias_ssh_key() {
  HOST=
  HOST_ALIAS=
  while [ $# -gt 0 ]; do
    key="$1"

    case $key in
      -h|--host)
        HOST="$2"
        shift # past argument
        shift # past value
        ;;
      -a|--alias)
        HOST_ALIAS="$2"
        shift # past argument
        shift # past value
        ;;
      *)    # unknown option
        shift # past argument
        ;;
    esac
  done
  
  [ -z "$HOST" ] && die "--host not specified"
  [ -z "$HOST_ALIAS" ] && die "--additional-host not specified"

  # TODO - check to see if the source host exists and die if not
  # TODO - check to see if the host alias doesn't exist and die if it does
  # TODO - better host processing code
  sed -i s'/Host $HOST/Host $HOST $HOST_ALIAS/' "$SSH_HOSTS_FILE"
}

rotate_ssh_key() {
  HOST=
  COMMENT=
  SKIP_PASSWORD=0
  while [ $# -gt 0 ]; do
    key="$1"

    case $key in
      -h|--host)
        HOST="$2"
        shift # past argument
        shift # past value
        ;;
      -c|--comment)
        COMMENT="$2"        
        shift # past argument
        shift # past value
        ;;
      -n|--no-password)
        SKIP_PASSWORD=1        
        shift # past argument
        ;;
      *)    # unknown option
        shift # past argument
        ;;
    esac
  done
  
  [ -z "$HOST" ] && die "--host not specified"
  [ -z "$COMMENT" ] && die "--comment not specified"
  
  KEY_BASE_NAME="id_$HOST"
  PRIVATE_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME"
  PUBLIC_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME.pub"
  # TODO - Die if existing keys are not found
  # TODO - Backup existing keys at this point
  
  [ -f "$PRIVATE_KEY_FILENAME" ] && die "Private key already exists: $PRIVATE_KEY_FILENAME"
  [ -f "$PUBLIC_KEY_FILENAME" ] && die "Public key already exists: $PUBLIC_KEY_FILENAME"
  
  echo "Creating new SSH key for $HOST"
  echo "Comment: $COMMENT"
  echo "Private Key: $PRIVATE_KEY_FILENAME"
  echo "Public Key: $PRIVATE_KEY_FILENAME"
  [ "$SKIP_PASSWORD" -eq "1" ] && ssh-keygen -a "$SSH_KEY_ROUNDS" -t "$SSH_KEY_ALGORITHM" -C "$COMMENT" -P "" -f "$PRIVATE_KEY_FILENAME" 
  [ "$SKIP_PASSWORD" -eq "0" ] && ssh-keygen -a "$SSH_KEY_ROUNDS" -t "$SSH_KEY_ALGORITHM" -C "$COMMENT" -f "$PRIVATE_KEY_FILENAME"
  
  [ -f "$PUBLIC_KEY_FILENAME" ] && cat "$PUBLIC_KEY_FILENAME"
}

revoke_ssh_key()
{
  HOST=
  while [ $# -gt 0 ]; do
    key="$1"

    case $key in
      -h|--host)
        HOST="$2"
        shift # past argument
        shift # past value
        ;;
      *)    # unknown option
        shift # past argument
        ;;
    esac
  done
  
  [ -z "$HOST" ] && die "--host not specified"
  
  KEY_BASE_NAME="id_$HOST"
  PRIVATE_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME"
  PUBLIC_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME.pub"
  [ ! -f "$PRIVATE_KEY_FILENAME" ] && die "Private key does not exist: $PRIVATE_KEY_FILENAME"
  [ ! -f "$PUBLIC_KEY_FILENAME" ] && die "Public key does not exist: $PUBLIC_KEY_FILENAME"

  # TODO - Die if existing keys are not found
  # TODO - Backup existing keys at this point
  # TODO - Remove host entry from SSH config
  # TODO - better host processing code
}

show_ssh_key() {
  HOST=
  while [ $# -gt 0 ]; do
    key="$1"

    case $key in
      -h|--host)
        HOST="$2"
        shift # past argument
        shift # past value
        ;;
      *)    # unknown option
        shift # past argument
        ;;
    esac
  done
  
  [ -z "$HOST" ] && die "--host not specified"
  
  KEY_BASE_NAME="id_$HOST"
  PRIVATE_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME"
  PUBLIC_KEY_FILENAME="$SSH_KEY_DIR/$KEY_BASE_NAME.pub"
  [ ! -f "$PRIVATE_KEY_FILENAME" ] && die "Private key does not exist: $PRIVATE_KEY_FILENAME"
  [ ! -f "$PUBLIC_KEY_FILENAME" ] && die "Public key does not exist: $PUBLIC_KEY_FILENAME"
  [ -f "$PUBLIC_KEY_FILENAME" ] && cat "$PUBLIC_KEY_FILENAME"
}

[ $# -lt 1 ] && die "No action specified"

ACTION=$1
shift

if [ "$ACTION" = "create" ]; then
  create_ssh_key "$@"
elif [ "$ACTION" = "alias" ]; then  
  alias_ssh_key "$@"
elif [ "$ACTION" = "revoke" ]; then
  revoke_ssh_key "$@"
elif [ "$ACTION" = "rotate" ]; then
  rotate_ssh_key "$@"
elif [ "$ACTION" = "show" ]; then
  show_ssh_key "$@"
elif [ "$ACTION" = "help"  ] || [ "$ACTION" = "--?" ] || [ "$ACTION" = "--help" ]; then
  echo "$0"
  echo "$0 create --host <host> --comment <comment> [--no-password]"
  echo "$0 alias --host <host> --additional-host <host>"
  echo "$0 revoke --host <host>"
  echo "$0 rotate --host <host> --comment <comment> [--no-password]"
  echo "$0 show --host <host>"
else
  die "Unknown action: $ACTION"
fi
