#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

STREAMER=$1
[ -z "$STREAMER" ] && die "Streamer not specified"

while true
do 
  streamlink --player=mpv "https://twitch.tv/$STREAMER" best > /dev/null 2>&1
  sleep 60
done
