#! /bin/sh

if [ -f /usr/bin/topgrade ]; then
  /usr/bin/topgrade -y \
        --disable=containers \
        --disable=dotnet \
        --disable=jetbrains_aqua \
        --disable=jetbrains_clion \
        --disable=jetbrains_datagrip \
        --disable=jetbrains_dataspell \
        --disable=jetbrains_gateway \
        --disable=jetbrains_goland \
        --disable=jetbrains_idea \
        --disable=jetbrains_mps \
        --disable=jetbrains_phpstorm \
        --disable=jetbrains_pycharm \
        --disable=jetbrains_rider \
        --disable=jetbrains_rubymine \
        --disable=jetbrains_rustrover \
        --disable=jetbrains_toolbox \
        --disable=node 
else

  [ -f /usr/bin/flatpak ] && flatpak update -y

  if [ -f /usr/bin/yay ]; then 
    yay -Syu --noconfirm
    sudo rm -fr /var/cache/pacman/pkg/download-*
    yay -Sc --noconfirm
  else
    sudo pacman -Syu --noconfirm
  fi

fi

[ -f "$HOME/work/personal/credfeto-systemd/install" ] && "$HOME/work/personal/credfeto-systemd/install"
