#! /bin/sh
[ -f /usr/bin/flatpak ] && flatpak update -y

if [ -f /usr/bin/yay ]; then 
	yay -Syu --noconfirm && yay -Sc --noconfirm
else
	sudo pacman -Syu --noconfirm
fi

[ -f /usr/bin/docker ] && \
   [ -f /usr/bin/docker-compose ] && \
   [ -d /home/markr/work/personal/scripts/docker/baget ] && \
   [ ! -f "$HOME/.no-baget" ] && \
   cd /home/markr/work/personal/scripts/docker/baget && \
   sudo docker compose pull && \
   sudo docker compose up -d && \
   cd

[ -f "$HOME/work/personal/credfeto-systemd/install" ] && "$HOME/work/personal/credfeto-systemd/install"
