#! /bin/sh

ssh root@192.168.86.1  "tcpdump -i pppoe0 tcp port 443 or udp port 443 -U -w - " | tshark -l -n -r - -Y "tls.handshake.extensions_server_name" -Tfields -e frame.time -e ip.src -e tls.handshake.extensions_server_name
