#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR=$(dirname "$(readlink -f "$0")")

[ -f /usr/bin/wg ] || die "Missing wireguard-tools || pacman -S wireguard-tools"

CLIENT_IP_ADDRESSES=
DNS=
PEER_PUBLIC_KEY=
PEER_ENDPOINT=
SAVE_TO=

while [ $# -gt 0 ]; do
    key="$1"

  case $key in
    -c|--client-ip)
      CLIENT_IP_ADDRESSES="$2"
      shift # past argument
      shift # past value
      ;;
    -d|--dns)
      DNS="$2"
      shift # past argument
      shift # past value
      ;;
    -p|--peer-endpoint)
      PEER_ENDPOINT="$2"
      shift # past argument
      shift # past value
      ;;      
    -f|--filename)
          SAVE_TO="$2"
          shift # past argument
          shift # past value
          ;;
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

[ -f "$HOME/.wg-endpoint" ] && . "$HOME/.wg-endpoint" 

[ -z "$CLIENT_IP_ADDRESSES" ] && die "Client IP Addresses not specified"
[ -z "$DNS" ] && die "DNS Addresses not specified"
[ -z "$PEER_PUBLIC_KEY" ] && die "Peer public key not specified"
[ -z "$PEER_ENDPOINT" ] && die "Peer address and port not specified"
[ -z "$SAVE_TO" ] && die "filename.conf to save the config to not specified"

PRIVATE_KEY=$(wg genkey)
PRESHARED_KEY=$(wg genpsk)
PUBLIC_KEY=$(echo "$PRIVATE_KEY" | wg genkey)

{
  echo "[Interface]"
  echo "# Public Key: $PUBLIC_KEY"
  echo "PrivateKey = $PRIVATE_KEY"
  echo "Address = $CLIENT_IP_ADDRESSES"
  echo "DNS = 10.20.10.1"
  echo ""
  echo "[Peer]"
  echo "PublicKey = $PEER_PUBLIC_KEY"
  echo "PresharedKey = $PRESHARED_KEY"
  echo "Endpoint = $PEER_ENDPOINT"  
  echo "AllowedIPs = 0.0.0.0/0,::/0"
  echo "PersistentKeepalive = 5"

} | tee "$SAVE_TO"
