version: "3"
 
services:
 
  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900
      - 7359:7359
    volumes:
      - /home/markr/.config/jellyfin:/config
      - /home/markr/.cache/jellyfin:/cache
      - /home/markr/Podcasts:/media
    restart: 'unless-stopped'
