# Version is now obsolete
#version: "3.8"
 
services:
 
  nuget:
    image: loicsharma/baget:latest
    container_name: nuget
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/db/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - Logging__Console__LogLevel__Default=Warning
    volumes:
      - /cache/baget/packages/nuget:/var/baget/packages
      - /cache/baget/db/nuget:/var/baget/db
    healthcheck:
      test: curl --fail http://localhost/v3/index.json || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  funfair-release:
    image: loicsharma/baget:latest
    container_name: funfair-release
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/db/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://dotnet-nuget.s3.eu-west-1.amazonaws.com/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - Logging__Console__LogLevel_Default=Warning
    volumes:
      - /cache/baget/packages/funfair-release:/var/baget/packages
      - /cache/baget/db/funfair-release:/var/baget/db
    healthcheck:
      test: curl --fail http://localhost/v3/index.json || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  funfair-prerelease:
    image: loicsharma/baget:latest
    container_name: funfair-prerelease
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/db/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - Logging__Console__LogLevel_Default=Warning
    volumes:
      - /cache/baget/packages/funfair-prerelease:/var/baget/packages
      - /cache/baget/db/funfair-prerelease:/var/baget/db
    healthcheck:
      test: curl --fail http://localhost/v3/index.json || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    ports:
      - 5555:443
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5


