# Version is now obsolete
#version: "3.8"
 
services:

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: nuget
      POSTGRES_PASSWORD: nuget
    ports:
      - 5432:5432
    volumes:
      - /db/postgresql/nuget:/var/lib/postgresql/data

  nuget:
    image: bagetter/bagetter:latest
    container_name: nuget
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/data/packages
      - Database__Type=PostgreSql
      - Database__ConnectionString=Server=postgresql;Port=5432;Database=nuget;User Id=nuget;Password=nuget;
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - MaxPackageSizeGiB=10
      - Logging__Console__LogLevel__Default=Information
      #- Kestrel__Endpoints__Http__Url=http://localhost:8080
    volumes:
      - /cache/baget/security/nuget:/root/.aspnet
      - /cache/baget/packages/nuget:/data/packages
      - /cache/baget/db/nuget:/data/db
    depends_on:
      postgresql:
        condition: service_started
#    ports:
#      - 8080:8080
#    healthcheck:
#      test: curl --fail http://127.0.0.1:8080/health || exit 1
#      interval: 5s
#      timeout: 4s
#      retries: 5

  funfair-release:
    image: bagetter/bagetter:latest
    container_name: funfair-release
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/data/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/data/db/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://dotnet-nuget.s3.eu-west-1.amazonaws.com/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - MaxPackageSizeGiB=10
      - Logging__Console__LogLevel_Default=Information
      #- Kestrel__Endpoints__Http__Url=http://localhost:8080
    volumes:
      - /cache/baget/security/nuget:/root/.aspnet
      - /cache/baget/packages/funfair-release:/data/packages
      - /cache/baget/db/funfair-release:/data/db
#    ports:
#      - 8081:8080
#    healthcheck:
#      test: curl --fail http://127.0.0.1:8080/health || exit 1
#      interval: 5s
#      timeout: 4s
#      retries: 5

  funfair-prerelease:
    image: bagetter/bagetter:latest
    container_name: funfair-prerelease
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/data/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/data/db/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - MaxPackageSizeGiB=10
      - Logging__Console__LogLevel_Default=Information
      #- Kestrel__Endpoints__Http__Url=http://localhost:8080
    volumes:
      - /cache/baget/security/nuget:/root/.aspnet
      - /cache/baget/packages/funfair-prerelease:/data/packages
      - /cache/baget/db/funfair-prerelease:/data/db
#    ports:
#      - 8082:8080
#    healthcheck:
#      test: curl --fail http://127.0.0.1:8080/health || exit 1
#      interval: 5s
#      timeout: 4s
#      retries: 5

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    ports:
      - 5555:443
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      nuget:
        condition: service_started
      funfair-prerelease:
        condition: service_started
      funfair-release:
        condition: service_started

  cache:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: cache
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - ./cache/populate:/root/populate
      - ./cache/nuget.config:/root/.nuget/NuGet/NuGet.Config
    command:
      /root/populate
