version: "3"
 
services:
 
  nuget:
    image: loicsharma/baget:latest
    hostname: baget-nuget
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ports:
      - 5555:80
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - Logging__Console__LogLevel__Default=Debug
#      - Kestrel__Endpoints__Https__Url=https://localhost
#      - Kestrel__Endpoints__Https__Certificate__Path=/server.pfx
#      - ASPNETCORE_URLS=https://localhost
    volumes:
      - /home/markr/docker/baget-data/nuget:/var/baget
      - /home/markr/work/personal/scripts/baget/server.pfx:/server.pfx

  funfair:
    image: loicsharma/baget:latest
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ports:
      - 5556:80 
    environment:
      - ApiKey=Upload
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=Sqlite
      - Database__ConnectionString=Data Source=/var/baget/baget.db
      - Search__Type=Database
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://dotnet-nuget.s3.eu-west-1.amazonaws.com/index.json
      - Mirror__PackageDownloadTimeoutSeconds=600
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
      - Logging__Console__LogLevel_Default=Debug
    volumes:
      - /home/markr/docker/baget-data/funfair:/var/baget
