logLevel: warn
database:
  evmJsonRpcCache:
    connectors:
      - id: postgresql
        driver: postgresql
        postgresql:
          connectionUri: postgres://erpc:erpc@postgresql:5432/erpc
          table: rpc_cache
    policies:
      - network: "*"
        connector: "postgresql"

server:
  httpHostV4: 0.0.0.0
  httpPort: 4000
metrics:
  enabled: false
  hostV4: 0.0.0.0
  port: 4001
projects:
  - id: main
    networks:
      # Ethereum Mainnet
      - architecture: evm
        evm:
          chainId: 1
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 3
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
          hedge:
            delay: 3000ms
            maxCount: 2

      # Optimism
      - architecture: evm
        evm:
          chainId: 10
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2


      # BSC
      - architecture: evm
        evm:
          chainId: 56
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # Gnosis
      - architecture: evm
        evm:
          chainId: 100
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # Polygon
      - architecture: evm
        evm:
          chainId: 137
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # Base
      - architecture: evm
        evm:
          chainId: 8453
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # Evmos
      - architecture: evm
        evm:
          chainId: 9001
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # EthereumPOW
      - architecture: evm
        evm:
          chainId: 10001
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # Arbitrum
      - architecture: evm
        evm:
          chainId: 42161
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

      # Avalanche
      - architecture: evm
        evm:
          chainId: 43114
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxAttempts: 5
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 200ms
          hedge:
            delay: 1000ms
            maxCount: 2

    upstreams:
      # Ethereum Mainnet
      - id: ff-ethereum-mainnet-1
        type: evm
        endpoint: https://1.mainnet.geth.clients.funfair.io
        evm:
          chainId: 1
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: ff-ethereum-mainnet-2
        type: evm   
        endpoint: https://2.mainnet.geth.clients.funfair.io
        evm:
          chainId: 1    
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: ff-ethereum-mainnet-3
        type: evm   
        endpoint: https://3.mainnet.geth.clients.funfair.io
        evm:
          chainId: 1    
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
            
      # Optimism
      - id: op-mainnet-1
        type: evm
        endpoint: https://mainnet.optimism.io
        evm:
          chainId: 10
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms

      # BSC
      - id: bsc-mainnet-1
        type: evm
        endpoint: https://bsc-dataseed1.bnbchain.org
        evm:
          chainId: 56
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms

      # Gnosis
      - id: ff-gnosis-mainnet-1
        type: evm
        endpoint: https://1.gnosis.nethermind.clients.funfair.io
        evm:
          chainId: 100
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: ff-gnosis-mainnet-2
        type: evm
        endpoint: https://2.gnosis.nethermind.clients.funfair.io
        evm:
          chainId: 100
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: ff-gnosis-mainnet-3
        type: evm
        endpoint: https://3.gnosis.nethermind.clients.funfair.io
        evm:
          chainId: 100
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
            
      # Polygon
      - id: polygon-mainnet-1
        type: evm
        endpoint: https://polygon-rpc.com
        evm:
          chainId: 137
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      
      # Base
      - id: base-mainnet-1
        type: evm
        endpoint: https://mainnet.base.org
        evm:
          chainId: 8453
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      
      # Evmos
      - id: evmos-mainnet-1
        type: evm
        endpoint: https://evmos-evm.publicnode.com
        evm:
          chainId: 9001
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      
      # EthereumPOW
      - id: ethereumpow-mainnet-1
        type: evm
        endpoint: https://mainnet.ethereumpow.org
        evm:
          chainId: 10001
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      
      # Arbitrum
      - id: arbitrum-mainnet-1
        type: evm
        endpoint: https://arb1.arbitrum.io
        evm:
          chainId: 42161
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      
      # Avalanche
      - id: ff-avalanche-mainnet-4
        type: evm
        endpoint: https://4.avax.avalanchego.clients.funfair.io/ext/bc/C/rpc
        evm:
          chainId: 43114
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: ff-avalanche-mainnet-5
        type: evm
        endpoint: https://5.avax.avalanchego.clients.funfair.io/ext/bc/C/rpc
        evm:
          chainId: 43114
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      - id: ff-avalanche-mainnet-6
        type: evm
        endpoint: https://6.avax.avalanchego.clients.funfair.io/ext/bc/C/rpc
        evm:
          chainId: 43114
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxAttempts: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
      

rateLimiters:
  budgets:
    - id: default-budget
      rules:
        - method: '*'
          maxCount: 10000
          period: 1s
    - id: global-blast
      rules:
        - method: '*'
          maxCount: 1000
          period: 1s
    - id: global-quicknode
      rules:
        - method: '*'
          maxCount: 300
          period: 1s
