#!/bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"

SERVER=
DB=
USER=
PASSWORD=
SCHEMA=

# Not following: 
# shellcheck disable=1091
. "$BASEDIR/dbenv" 

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -d|--database)
      DB="$2"
      shift # past argument
      shift # past value
      ;;
    -f|--file)
      SCHEMA="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

[ -z "$SERVER" ] && die "--server not specified"
[ -z "$DB" ] && die "--database not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"

sqlcmd -C -S "$SERVER" -U "$USER" -P "$PASSWORD" -b -e -Q "CREATE DATABASE $DB"

[ -n "$SCHEMA" ] && sqlcmd -C -S "$SERVER" -U "$USER" -P "$PASSWORD" -d "$DB" -b -e -i "$SCHEMA"
