#!/bin/sh

PROG=$0

error_exit() {
    echo
    echo "$@"
    exit 1
}
#Trap the killer signals so that we can exit with a good message.
trap "error_exit 'Received signal SIGHUP'" SIGHUP
trap "error_exit 'Received signal SIGINT'" SIGINT
trap "error_exit 'Received signal SIGTERM'" SIGTERM

shopt -s expand_aliases
alias die='error_exit "Error $PROG (@`echo $(( $LINENO - 1 ))`):"'

BASEDIR=$(dirname "$(readlink -f "$0")")
echo "Script Dir: $BASEDIR"

SERVER=
DB=
USER=
PASSWORD=
SCHEMA=

source $BASEDIR/dbenv 

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -d|--database)
      DB="$2"
      shift # past argument
      shift # past value
      ;;
    -f|--file)
      SCHEMA="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

[ -z "$SERVER" ] && die "--server not specified"
[ -z "$DB" ] && die "--database not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"

sqlcmd -C -S "$SERVER" -U "$USER" -P "$PASSWORD" -b -e -Q "CREATE DATABASE $DB"

[ -n "$SCHEMA" ] && sqlcmd -C -S "$SERVER" -U "$USER" -P "$PASSWORD" -d "$DB" -b -e -i "$SCHEMA"
