#!/bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

SOURCE=
OUTPUT=
REPORT=
LOG=

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -f|--files)
      SOURCE="$2"
      shift # past argument
      shift # past value
      ;;
    -o|--output)
      OUTPUT="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      die "unknown argument $1"
      ;;
  esac
done

[ -z "$SOURCE" ] && die "--files not specified"
[ -z "$OUTPUT" ] && die "--output not specified"

FILTER="$SOURCE/Filter.scpf"
LOG="$OUTPUT.log"
REPORT="$OUTPUT.xml"

sqlcompare \
  /filter:"$FILTER" \
  /options:ConsiderNextFilegroupInPartitionSchemes,DecryptPost2kEncryptedObjects,DoNotOutputCommentHeader,ForceColumnOrder,IgnoreCertificatesAndCryptoKeys,IgnoreDatabaseAndServerName,IgnoreUserProperties,IgnoreUsersPermissionsAndRoleMemberships,IgnoreWhiteSpace,IgnoreWithElementOrder,IncludeDependencies,NoDeploymentLogging,ThrowOnFileParseFailed,UseCompatibilityLevel \
  /transactionIsolationLevel:SERIALIZABLE \
  /include:staticData \
  /scriptFile:"$OUTPUT" \
  /showWarnings \
  /include:Identical \
  /report:"$REPORT" \
  /reportType:Xml \
  /force \
  /OutputWidth:1024 \
  /scripts1:"$SOURCE" \
  /out:"$LOG" \
  /empty2 \
  /assertidentical

