#!/bin/sh

PROG=$0
BASEDIR="$(dirname "$(readlink -f "$0")")"

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"
SERVER=
DB=

. "$BASEDIR/dbenv" 

[ -z "$SERVER" ] && die "--server not specified"
[ -z "$DB" ] && die "--database not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"

dotnet pwsh -f "$BASEDIR/../powershell/DBAppSettings.ps1" --server "$SERVER" --user "$USER" --password "$PASSWORD" --database "$DB"

