#!/bin/sh

CURRENT_DIR=$PWD
echo "Current Dir: $CURRENT_DIR"

die() {
    echo
    echo "$@"
    exit 1
}

SERVER=
DB=
USER=
PASSWORD=
SCHEMA=

DB_SETTINGS_FILE=~/.database
[ -f "$DB_SETTINGS_FILE" ]; echo "Using $DB_SETTINGS_FILE"
[ -f "$DB_SETTINGS_FILE" ]; . "$DB_SETTINGS_FILE"

LOCAL_DB_SETTINGS_FILE=$(find $(CP="${PWD}"; while [ -n "$CP" ] ; do echo "$CP"; CP="${CP%/*}"; done;) -mindepth 1 -maxdepth 1 -type f -name ".database" | head -n 1)
if [ ! -z "$LOCAL_DB_SETTINGS_FILE" ]; then
  LOCAL_DB_SETTINGS_FILE=$(readlink -f "$LOCAL_DB_SETTINGS_FILE")
  LOCAL_DB_SETTINGS_FOLDER=$(dirname "$LOCAL_DB_SETTINGS_FILE")
  if [ "$LOCAL_DB_SETTINGS_FILE" != "$DB_SETTINGS_FILE" ]; then
    echo "Using settings from $LOCAL_DB_SETTINGS_FOLDER"
    . "$LOCAL_DB_SETTINGS_FILE"
    
    if [ ! -z "$DB" ]; then
      [ -z "$SOURCE" ] && SOURCE="$LOCAL_DB_SETTINGS_FOLDER/db"
      REDGATE=~/.redgate
      [ ! -d "$REDGATE" ] && mkdir $REDGATE
      [ -z "$OUTPUT" ] && OUTPUT=$REDGATE/$DB.sql
    fi
  fi
fi

parse_cmdline() {

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -U|--user)
      USER="$2"
      shift # past argument
      shift # past value
      ;;
    -P|--password)
      PASSWORD="$2"
      shift # past argument
      shift # past value
      ;;
    -s|--server)
      SERVER="$2"
      shift # past argument
      shift # past value
      ;;
    -d|--database)
      DB="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option - skip here      
      shift # past argument
      ;;
  esac
done
}

parse_cmdline $@

[ -z "$SERVER" ] && die "--server not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"

SQLCOMPARE_SERVER=$SERVER
if [ "$SERVER" = "localhost" ]; then
  SQLCOMPARE_SERVER=$(sudo docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mssql)
  if [ ! -z "$SQLCOMPARE_SERVER" ]; then
    echo "Overriding localhost with Docker Server for compare at $SQLCOMPARE_SERVER"    
  fi  
fi

echo "Server: $SERVER"
echo "User: $USER"
[ ! -z "$DB" ] && echo "DB: $DB"
[ ! -z "$SOURCE" ] && echo "Source: $SOURCE"
[ ! -z "$OUTPUT" ] && echo "Output: $OUTPUT"

