#!/bin/sh

BASEDIR="$(dirname "$(readlink -f "$0")")"
SERVER=
DB=

# Not following:
# shellcheck disable=1091
. "$BASEDIR/dbenv"

info "Script Dir: $BASEDIR"

[ -z "$SERVER" ] && die "--server not specified"
[ -z "$DB" ] && die "--database not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"


info "Dropping database $DB if it exists"
sqlcmd -C -S "$SERVER" -U "$USER" -P "$PASSWORD" -b -e -Q "IF EXISTS(SELECT Name from sys.Databases WHERE name = '$DB') ALTER DATABASE $DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE" || die "Could not set $DB to single-user mode"
sqlcmd -C -S "$SERVER" -U "$USER" -P "$PASSWORD" -b -e -Q "IF EXISTS(SELECT Name from sys.Databases WHERE name = '$DB') DROP DATABASE $DB" || die "Could not drop database $DB"
success "Database $DB dropped"
