#!/bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"
SERVER=
DB=

# Not following: 
# shellcheck disable=1091
. "$BASEDIR/dbenv" 

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -o|--output)
      OUTPUT="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

[ -z "$SERVER" ] && die "--server not specified"
[ -z "$DB" ] && die "--database not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"
[ -z "$OUTPUT" ] && die "--output not specified"

FILTER="$OUTPUT/Filter.scpf"

DBXML="$TMP/db.xml"
HOOKSXML="$TMP/hooks.xml"

cat << EOF > "$HOOKSXML"
<?xml version="1.0" encoding="utf-16" standalone="yes"?>
<HooksConfig version="1" type="HooksConfig">
 <Name>Working Folder</Name>
 <Commands type="Commands" version="2">
   <element>
     <key type="string">GetLatest</key>
     <value version="1" type="GenericHookCommand">
       <CommandLine></CommandLine>
       <Verify>exitCode == 0</Verify>
     </value>
   </element>
   <element>
     <key type="string">Add</key>
     <value version="1" type="GenericHookCommand">
       <CommandLine></CommandLine>
       <Verify>exitCode == 0</Verify>
     </value>
   </element>
   <element>
     <key type="string">Edit</key>
     <value version="1" type="GenericHookCommand">
       <CommandLine></CommandLine>
       <Verify>exitCode == 0</Verify>
     </value>
   </element>
   <element>
     <key type="string">Delete</key>
     <value version="1" type="GenericHookCommand">
       <CommandLine></CommandLine>
       <Verify>exitCode == 0</Verify>
     </value>
   </element>
   <element>
     <key type="string">Commit</key>
     <value version="1" type="GenericHookCommand">
       <CommandLine></CommandLine>
       <Verify>exitCode == 0</Verify>
     </value>
   </element>
   <element>
     <key type="string">Revert</key>
     <value version="1" type="GenericHookCommand">
       <CommandLine></CommandLine>
       <Verify>exitCode == 0</Verify>
     </value>
   </element>
 </Commands>
</HooksConfig>
EOF


cat << EOF > "$DBXML"
<?xml version="1.0" encoding="utf-16" standalone="yes"?> 
<!-- -->
<ISOCCompareLocation version="2" type="WorkingFolderGenericLocation" >
  <LocalRepositoryFolder>%SOURCE%</LocalRepositoryFolder>
  <HooksConfigFile>$HOOKSXML</HooksConfigFile>
  <HooksFileInRepositoryFolder>False</HooksFileInRepositoryFolder>
</ISOCCompareLocation>
EOF

sudo "$BASEDIR/sqlcompare" \
  "$HOME" \
  /filter:"$FILTER" \
  /options:ConsiderNextFilegroupInPartitionSchemes,DecryptPost2kEncryptedObjects,DoNotOutputCommentHeader,ForceColumnOrder,IgnoreCertificatesAndCryptoKeys,IgnoreDatabaseAndServerName,IgnoreUserProperties,IgnoreUsersPermissionsAndRoleMemberships,IgnoreWhiteSpace,IgnoreWithElementOrder,IncludeDependencies,NoDeploymentLogging,ThrowOnFileParseFailed,UseCompatibilityLevel \
  /transactionIsolationLevel:SERIALIZABLE \
  /makescripts:"$OUTPUT" \
  /force \
  /OutputWidth:1024 \
  /server1:"$SQLCOMPARE_SERVER" \
  /database1:"$DB" \
  /username1:"$USER" \
  /password1:"$PASSWORD"
  
