#! /bin/sh
docker pull mcr.microsoft.com/mssql/server:2019-latest

PASSWORD=LocalDb1234$
docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$PASSWORD" -e "MSSQL_PID=Developer"  -p 1433:1433  --name mssql --hostname sql -d mcr.microsoft.com/mssql/server:2019-latest
