#!/bin/sh
USER_HOME=$1
shift # past argument

die() {
    echo
    echo "$@"
    exit 1
}

#SQLCOMPARE_VERSION=15.3.13
SQLCOMPARE_VERSION=latest

docker pull redgate/sqlcompare:$SQLCOMPARE_VERSION
echo "docker run --rm \
        --interactive \
        --tty \
        --mount type=bind,src=$USER_HOME,dst=$USER_HOME \
        --network multi-host-network \
        -e REDGATE_LICENSING_PAT_EMAIL=$REDGATE_EMAIL \
        -e REDGATE_LICENSING_PAT_TOKEN=$REDGATE_PAT \
        redgate/sqlcompare:$SQLCOMPARE_VERSION \
        /IAgreeToTheEULA \
        $*"  
docker run --rm \
  --interactive \
  --tty \
  --mount "type=bind,src=$USER_HOME,dst=$USER_HOME" \
  --network multi-host-network \
  "redgate/sqlcompare:$SQLCOMPARE_VERSION" \
  "$@" 
    
    
