#!/bin/bash
USER_HOME=$1
shift # past argument
MAP=$USER_HOME:$USER_HOME
echo "MAP: $MAP"
docker pull redgate/sqlcompare:latest
docker run  --rm --network multi-host-network -v$MAP redgate/sqlcompare:latest /IAgreeToTheEULA "$@"
