#!/bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"
SOURCE=
SERVER=
USER=
DB=
OUTPUT=
REPORT=
LOG=

# Not following: 
# shellcheck disable=1091
. "$BASEDIR/dbenv"

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -d|--database)
      DB="$2"
      shift # past argument
      shift # past value
      ;;
    -f|--files)
      SOURCE="$2"
      shift # past argument
      shift # past value
      ;;
    -o|--output)
      OUTPUT="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      shift # past argument
      ;;
  esac
done

[ -z "$SOURCE" ] && die "--files not specified"
[ -z "$OUTPUT" ] && die "--output not specified"
[ -z "$SERVER" ] && die "--server not specified"
[ -z "$DB" ] && die "--database not specified"
[ -z "$USER" ] && die "--user not specified"
[ -z "$PASSWORD" ] && die "--password not specified"

FILTER="$SOURCE/Filter.scpf"
LOG="$OUTPUT.log"
REPORT="$OUTPUT.xml"

[ -f "$OUTPUT" ] && sudo rm "$OUTPUT"

[ -z "$REDGATE_EMAIL" ] && die "REDGATE_EMAIL not specified"
[ -z "$REDGATE_PAT" ] && die "REDGATE_PAT not specified"
#  "/email:$REDGATE_EMAIL" \
#  "/token:$REDGATE_PAT" \

echo "Running sqlcompare to produce $OUTPUT"
sudo "$BASEDIR/sqlcompare" \
  "$HOME" \
  "/email:$REDGATE_EMAIL" \
  "/token:$REDGATE_PAT" \
  /IAgreeToTheEULA \
  /verbose \
  /log:VERBOSE \
  /filter:"$FILTER" \
  /options:CaseSensitiveObjectDefinition,ConsiderNextFilegroupInPartitionSchemes,DecryptPost2kEncryptedObjects,DoNotOutputCommentHeader,ForceColumnOrder,IgnoreCertificatesAndCryptoKeys,IgnoreDatabaseAndServerName,IgnoreUserProperties,IgnoreUsersPermissionsAndRoleMemberships,IgnoreWhiteSpace,IgnoreWithElementOrder,IncludeDependencies,NoDeploymentLogging,ThrowOnFileParseFailed,UseCompatibilityLevel \
  /transactionIsolationLevel:SERIALIZABLE \
  /include:staticData \
  /scriptFile:"$OUTPUT" \
  /scripts1:"$SOURCE" \
  /showWarnings \
  /include:Identical \
  /report:"$REPORT" \
  /reportType:Xml \
  /force \
  /OutputWidth:1024 \
  /out:"$LOG" \
  /server2:"$SQLCOMPARE_SERVER" \
  /database2:"$DB" \
  /username2:"$USER" \
  /password2:"$PASSWORD"
   
#   \
#  /assertidentical

#  /scriptFile:"$OUTPUT" \

[ ! -f "$LOG" ] && die "No log generated at $LOG"
[ -f "$LOG" ] && cat "$LOG"

[ ! -f "$OUTPUT" ] && die "No output generated at $OUTPUT"



echo "Running sqlcmd to import $OUTPUT"
sqlcmd \
  -C \
  -S "$SQLCOMPARE_SERVER" \
  -U "$USER" \
  -P "$PASSWORD" \
  -d "$DB" \
  -b \
  -e \
  -i "$OUTPUT"
