#! /bin/sh

export PATH="$PATH:/root/.dotnet/tools"

echo "HOME: $HOME"

echo "Installed SDKS:"
dotnet --list-sdks

echo "Waiting for start"
sleep 30


echo "Clearing everything"
dotnet nuget locals all --clear


echo "Restoring tools"
dotnet tool restore


TOOLS="sleet \
       TSQLLint \
       FunFair.BuildCheck \
       FunFair.BuildVersion \
       Credfeto.Changelog.Cmd \
       Credfeto.Package.Push \
       FunFair.Content.Packager.Cmd \
       FunFair.Content.PackageSigner.Cmd"

echo "Installing tools"
for PACKAGE in ${TOOLS}; do
    echo "Installing$package..."
    dotnet tool install --local "$PACKAGE" --create-manifest-if-needed
done

while true
do
    echo "Waiting for new packages"
    sleep 120

    for PACKAGE in ${TOOLS}; do
    do
        echo "Updating $package..."
        dotnet tool update --local "$PACKAGE"
    done
done
