#!/bin/bash

info() {
    echo "$@"
}

die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
info "Script Dir: $BASEDIR"


TOKEN=
REPO=

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -t|--token)
      TOKEN="$2"
      shift # past argument
      shift # past value
      ;;
    -r|--repo)
      REPO="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      die "unknown argument $1"
      ;;
  esac
done

[ -z "$TOKEN" ] && die "--token not specified"
[ -z "$REPO" ] && die "--repo not specified"


c=1
while [ "$c" -gt 0 ]
do
        c=0

        response=$(curl -s -H "Authorization: token $TOKEN" \
             "https://api.github.com/repos/$REPO/actions/runs?status=queued")

        ids=$(echo "$response" | \
             jq '.workflow_runs[] | select([.status] | inside(["queued"])) | .id')
        while IFS= read -r i; do
                [ -z "$i" ] && continue
                info "Cancelling $i..."
                curl \
                     --silent \
                     -H "Authorization: token $TOKEN" \
                     -X POST "https://api.github.com/repos/$REPO/actions/runs/$i/cancel" > /dev/null || die "Failed to cancel $i"
                c=$((c+1))
        done <<EOF
$ids
EOF

        info "Total $c in this batch"
done
