version: "3"
 
services:
 
  updater:
    image: nroi/flexo:latest
    hostname: flexo
    ports:
      - 7878:7878
    environment:
      - FLEXO_LISTEN_IP_ADDRESS=0.0.0.0
      - FLEXO_PORT=7878
      - FLEXO_CONNECT_TIMEOUT=3000
      - FLEXO_MIRROR_SELECTION_METHOD=auto
      - FLEXO_MIRRORS_AUTO_HTTPS_REQUIRED=true
      - FLEXO_MIRRORS_AUTO_IPV4=true
      - FLEXO_MIRRORS_AUTO_IPV6=false
      - FLEXO_NUM_VERSIONS_RETAIN=3
#    deploy:
#      replicas: 4
