#! /bin/sh

PACKAGES="com.brave.Browser \
          org.mozilla.firefox \
          com.opera.Opera \
          com.discordapp.Discord \
          com.spotify.Client \
          com.todoist.Todoist \
          com.bitwarden.desktop \
          org.mozilla.Thunderbird \
          com.github.iwalton3.jellyfin-media-player \
          com.ktechpit.whatsie"

for PACKAGE in $PACKAGES; do
  echo "* Installing $PACKAGE..."
  flatpak install -y "$PACKAGE"
done