name: Test-PR Lint
on: [pull_request]
jobs:
  include-JIRA-ticket:
    runs-on: ubuntu-latest
    steps:
#    - name: Branch
#      run: |
#         echo Head Ref ${{ github.head_ref }}
#         echo Is Release ${{ !startsWith(github.head_ref, 'release/') && !startsWith(github.head_ref, 'hotfix/' ) }}
    - if: ${{ !startsWith(github.head_ref, 'release/') && !startsWith(github.head_ref, 'hotfix/") }}
      uses: vijaykramesh/pr-lint-action@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}