name: Testing

on:
  push:
    branches:
    - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
        token: ${{ secrets.SOURCE_PUSH_TOKEN }}
    - uses: credfeto/action-dotnet-version-detect@v1.1.1
    - uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Enable dotnet tools
      run: dotnet new tool-manifest
    - name: Install Changelog tool
      run: dotnet tool install --local Credfeto.ChangeLog.Cmd
    - run: echo WHEN=`date +"%Y-%m-%d"` >> $GITHUB_ENV
    - run: echo ${{ env.WHEN }} > change.log
    - name: Add Changelog
      run: |
        git diff -s --exit-code || dotnet changelog -changelog CHANGELOG.md -add Changed -message "[FF-368] - Updated GEOIP DB from MaxMind (${{ env.WHEN}})"
        echo "Diff2"
        git diff
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[FF-368] - Updated GEOIP DB from MaxMind"
        file_pattern: "*.mmdb CHANGELOG.md"
        commit_user_name: "fun-geoip[bot]"
        commit_user_email: "credfeto@users.noreply.github.com"
        commit_author: "fun-geoip[bot] <credfeto@users.noreply.github.com>"
        skip_dirty_check: false